from engine.requirement_logic import (
    eval_biochar_applicability,
    eval_feedstock_requirements,
    eval_reactor_requirements,
    eval_storage_requirements,
    eval_monitoring_requirements,
    reactor_design_diagram,
    durability_option_declared,
    sampling_batch_definition,
    chain_of_custody_diagram,
    biochar_chemical_analysis,
    uncertainty_inputs,
    stockpiling_disclosure,
    adaptive_management_plan,
    feedstock_moisture_management,
    contaminant_monitoring_plan,
    product_standard_compliance,
    fuel_use_reversal_risk,
    sampling_plan_consistency,
    reactor_maintenance_plan,
    stack_emissions_monitoring_method,
    biochar_required_measurements,
    deployment_method_selected,
    direct_soil_application_evidence,
    reactor_material_selection,
    end_material_process_description,
    environmental_legal_requirements,
    regulatory_measurement_methods,
    biochar_characterization_approach,
    engineering_design_diagram,
    crediting_activity_boundaries,
    storage_system_boundary,
)

LOGIC_REGISTRY = {
    "eval_biochar_applicability": eval_biochar_applicability,
    "eval_feedstock_requirements": eval_feedstock_requirements,
    "eval_reactor_requirements": eval_reactor_requirements,
    "eval_storage_requirements": eval_storage_requirements,
    "eval_monitoring_requirements": eval_monitoring_requirements,
    "reactor_design_diagram": reactor_design_diagram,
    "durability_option_declared": durability_option_declared,
    "sampling_batch_definition": sampling_batch_definition,
    "chain_of_custody_diagram": chain_of_custody_diagram,
    "biochar_chemical_analysis": biochar_chemical_analysis,
    "uncertainty_inputs": uncertainty_inputs,
    "stockpiling_disclosure": stockpiling_disclosure,
    "adaptive_management_plan": adaptive_management_plan,
    "feedstock_moisture_management": feedstock_moisture_management,
    "contaminant_monitoring_plan": contaminant_monitoring_plan,
    "product_standard_compliance": product_standard_compliance,
    "fuel_use_reversal_risk": fuel_use_reversal_risk,
    "sampling_plan_consistency": sampling_plan_consistency,
    "reactor_maintenance_plan": reactor_maintenance_plan,
    "stack_emissions_monitoring_method": stack_emissions_monitoring_method,
    "biochar_required_measurements": biochar_required_measurements,
    "deployment_method_selected": deployment_method_selected,
    "direct_soil_application_evidence": direct_soil_application_evidence,
    "reactor_material_selection": reactor_material_selection,
    "end_material_process_description": end_material_process_description,
    "environmental_legal_requirements": environmental_legal_requirements,
    "regulatory_measurement_methods": regulatory_measurement_methods,
    "biochar_characterization_approach": biochar_characterization_approach,
    "engineering_design_diagram": engineering_design_diagram,
    "crediting_activity_boundaries": crediting_activity_boundaries,
    "storage_system_boundary": storage_system_boundary,
}
